### ISSUE TITLE
pip search xxx with Error

### ISSUE THREAD

**Issue by DavidIans** [pypa/pypa.io#66] opened 2020-12-16 10:37 UTC
It looks like `pip search` is not working

```
shell> pip3 search requests                    # pip search request is same too  pip3 search requests
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/cli/base_command.py", line 188, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/commands/search.py", line 48, in run
    pypi_hits = self.search(query, options)
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/commands/search.py", line 65, in search
    hits = pypi.search({'name': query, 'summary': query}, 'or')
  File "/usr/lib/python2.7/xmlrpclib.py", line 1243, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1602, in __request
    verbose=self.__verbose
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/download.py", line 1012, in request
    return self.parse_response(response.raw)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1493, in parse_response
    return u.close()
  File "/usr/lib/python2.7/xmlrpclib.py", line 800, in close
    raise Fault(**self._stack[0])
Fault: <Fault -32500: 'RuntimeError: This API has been temporarily disabled due to unmanageable load and will be deprecated in the near future. Please use the Simple or JSON API instead.'>
```

**Comment by di** [comment] 2020-12-16 20:45
Duplicate of https://github.com/pypa/pip/issues/9292. See https://github.com/pypa/pip/issues/5216#issuecomment-744605466 for more context.

**Closed by di** 2020-12-16 20:45 UTC
